[package]
name = "raulyrs"
version = "0.1.0"
edition = "2018"

[dependencies]
dotenv = "0.15.0"
tracing = "0.1.29"
tracing-subscriber = "0.2"
serde = {version = "1.0.130", features = ["derive"]}


[dependencies.tokio]
version = "1.0"
features = ["macros", "signal", "rt-multi-thread"]

[dependencies.serenity]
version = "0.10.9"
features = ["framework", "standard_framework"]

[dependencies.reqwest]
version = "0.11.5"
features = ["json"]