[package]
name = "raulyrs"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
scraper = "0.14.0"
rand = "0.8.5"
chrono = "0.4.23"
serde = {version = "1.0.152", features = ["derive"]}


[dependencies.tokio]
version = "1.21.2"
features = ["macros", "signal", "rt-multi-thread"]

[dependencies.serenity]
version = "0.11"
features = ["framework", "standard_framework"]

[dependencies.reqwest]
version = "0.11.14"
features = ["json"]
