name: Build Package

on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: cachix/cachix-action@v14
        with:
          name: frahz-pkgs
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build -L
